version: 0.2

phases:
  install:
    commands:
      - echo "Installing AWS SAM CLI"
      - yum install -y unzip
      - curl -Lo sam-installation.zip https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
      - unzip sam-installation.zip -d sam-installation
      - ./sam-installation/install
      - export PATH=$PATH:/usr/local/bin
      - sam --version

  build:
    commands:
      - cd functions/main
      - sam build
      - sam package --s3-bucket bmi-weight-tracker-api-demo --output-template-file outputtemplate.yaml
      - sam deploy --template-file outputtemplate.yaml --stack-name bmi-weight-tracker-main --capabilities CAPABILITY_IAM --s3-bucket bmi-weight-tracker-api-demo
artifacts:
  type: zip
  files:
    - template.yaml
    - outputtemplate.yaml