version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "bmi-weight-tracker-device"
s3_bucket = "bmi-weight-tracker-lambda-functions"
s3_prefix = "bmi-weight-tracker-device"
region = "us-east-2"
confirm_changeset= false
capabilities = "CAPABILITY_IAM"